name = "RandomWalk"
uuid = "53be4d88-e596-4e22-a109-faee6f30e8a3"
authors = ["Jonathan Miller jonathan.miller@fieldofnodes.com"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Geometries = "376103b7-462c-4dcb-a533-f8e48fa117d8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Distributions = "0.25"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
